#!/usr/bin/env ruby

require 'optparse'
require 'fileutils'
require 'csv'
require 'pry'

JOKES = [
  "Yo momma so fat, she broke the branch in her family tree!",
  "Yo Momma so fat, even Dora cant explore her.",
  "Yo Momma so stupid, she locked herself out of her motorcycle."
]
TASKS_FILE = "/home/naps62/.todo"

parser = OptionParser.new do |opts|
  opts.banner = "Usage: todo [options]"

  opts.on('-m', '--momma', 'joke about yo momma') do
    puts JOKES.sample
  end

  opts.on('-c', '--count', 'Counts the number of tasks on the list') do
    puts count
  end

  opts.on('a', '--add TASK', 'Adds TASK to the todo list') do |task|
    add task
  end

  opts.on('-d', '--done ID', Integer, 'Marks task with given ID as done') do |id|
    mark_as_done id
  end
end

def count
  File.read(TASKS_FILE).scan(/\n/).count
end

def add(task)
  CSV.open(TASKS_FILE, "a+") do |csv|
    csv << [false, task]
  end
end

def mark_as_done(id)
  tasks = CSV.read(TASKS_FILE)
  tasks[id-1][0] = true
  CSV.open(TASKS_FILE, 'wb') do |csv|
    tasks.each { |task| csv << task }
  end
end

parser.parse(ARGV)
